import type { MoldPreset } from "./types";

export const moldPresets: MoldPreset[] = [
  {
    product_type: "Panettone Alto",
    mold_rating: "100g",
    height_cm: 5.0,
    diameter_cm: 7.0,
    width_cm: null,
    length_cm: null,
    suggested_dough_weight_min_g: 110,
    suggested_dough_weight_max_g: 110,
    notes: "Standard Milanese shape",
  },
  {
    product_type: "Panettone Alto",
    mold_rating: "300g",
    height_cm: 8.5,
    diameter_cm: 11.0,
    width_cm: null,
    length_cm: null,
    suggested_dough_weight_min_g: 330,
    suggested_dough_weight_max_g: 330,
    notes: "Standard Milanese shape",
  },
  {
    product_type: "Panettone Alto",
    mold_rating: "500g",
    height_cm: 9.5,
    diameter_cm: 13.0,
    width_cm: null,
    length_cm: null,
    suggested_dough_weight_min_g: 550,
    suggested_dough_weight_max_g: 550,
    notes: "Standard Milanese shape",
  },
  {
    product_type: "Panettone Alto",
    mold_rating: "750g",
    height_cm: 11.0,
    diameter_cm: 15.0,
    width_cm: null,
    length_cm: null,
    suggested_dough_weight_min_g: 825,
    suggested_dough_weight_max_g: 825,
    notes: "Standard Milanese shape",
  },
  {
    product_type: "Panettone Alto",
    mold_rating: "1kg",
    height_cm: 12.5,
    diameter_cm: 17.0,
    width_cm: null,
    length_cm: null,
    suggested_dough_weight_min_g: 1100,
    suggested_dough_weight_max_g: 1100,
    notes: "Standard Milanese shape",
  },
  {
    product_type: "Panettone Basso",
    mold_rating: "500g",
    height_cm: 5.5,
    diameter_cm: 15.5,
    width_cm: null,
    length_cm: null,
    suggested_dough_weight_min_g: 550,
    suggested_dough_weight_max_g: 550,
    notes: "Galup style (low)",
  },
  {
    product_type: "Panettone Basso",
    mold_rating: "750g",
    height_cm: 6.0,
    diameter_cm: 18.5,
    width_cm: null,
    length_cm: null,
    suggested_dough_weight_min_g: 825,
    suggested_dough_weight_max_g: 825,
    notes: "Galup style (low)",
  },
  {
    product_type: "Panettone Basso",
    mold_rating: "1kg",
    height_cm: 7.0,
    diameter_cm: 21.0,
    width_cm: null,
    length_cm: null,
    suggested_dough_weight_min_g: 1100,
    suggested_dough_weight_max_g: 1100,
    notes: "Galup style (low). Diameter can vary 21-22cm.",
  },
  {
    product_type: "Pandoro",
    mold_rating: "80-100g",
    height_cm: 6.0,
    diameter_cm: null,
    width_cm: 8.0,
    length_cm: null,
    suggested_dough_weight_min_g: 90,
    suggested_dough_weight_max_g: 110,
    notes: "Star shape, width is top-width",
  },
  {
    product_type: "Pandoro",
    mold_rating: "500g",
    height_cm: 14.5,
    diameter_cm: null,
    width_cm: 19.5,
    length_cm: null,
    suggested_dough_weight_min_g: 530,
    suggested_dough_weight_max_g: 550,
    notes: "Star shape, width is top-width",
  },
  {
    product_type: "Pandoro",
    mold_rating: "750g",
    height_cm: 16.0,
    diameter_cm: null,
    width_cm: 21.0,
    length_cm: null,
    suggested_dough_weight_min_g: 780,
    suggested_dough_weight_max_g: 825,
    notes: "Star shape, width is top-width",
  },
  {
    product_type: "Pandoro",
    mold_rating: "1kg",
    height_cm: 17.0,
    diameter_cm: null,
    width_cm: 23.0,
    length_cm: null,
    suggested_dough_weight_min_g: 1050,
    suggested_dough_weight_max_g: 1100,
    notes: "Star shape, width is top-width",
  },
  {
    product_type: "Colomba",
    mold_rating: "100g",
    height_cm: null,
    diameter_cm: null,
    width_cm: 9.0,
    length_cm: 13.0,
    suggested_dough_weight_min_g: 100,
    suggested_dough_weight_max_g: 110,
    notes: "Dove shape",
  },
  {
    product_type: "Colomba",
    mold_rating: "300g",
    height_cm: null,
    diameter_cm: null,
    width_cm: 15.0,
    length_cm: 22.0,
    suggested_dough_weight_min_g: 270,
    suggested_dough_weight_max_g: 300,
    notes: "Dove shape",
  },
  {
    product_type: "Colomba",
    mold_rating: "500g",
    height_cm: null,
    diameter_cm: null,
    width_cm: 18.0,
    length_cm: 26.0,
    suggested_dough_weight_min_g: 450,
    suggested_dough_weight_max_g: 500,
    notes: "Dove shape. Use lower weight if glazing.",
  },
  {
    product_type: "Colomba",
    mold_rating: "750g",
    height_cm: null,
    diameter_cm: null,
    width_cm: 20.0,
    length_cm: 29.0,
    suggested_dough_weight_min_g: 675,
    suggested_dough_weight_max_g: 750,
    notes: "Dove shape. Use lower weight if glazing.",
  },
  {
    product_type: "Colomba",
    mold_rating: "1kg",
    height_cm: null,
    diameter_cm: null,
    width_cm: 22.0,
    length_cm: 32.0,
    suggested_dough_weight_min_g: 900,
    suggested_dough_weight_max_g: 1000,
    notes: "Dove shape. Use lower weight if glazing.",
  },
  {
    product_type: "Panettone Gastronomico",
    mold_rating: "500g",
    height_cm: 9.5,
    diameter_cm: 13.0,
    width_cm: null,
    length_cm: null,
    suggested_dough_weight_min_g: 500,
    suggested_dough_weight_max_g: 530,
    notes: "Savory brioche - flat top",
  },
  {
    product_type: "Panettone Gastronomico",
    mold_rating: "750g",
    height_cm: 11.0,
    diameter_cm: 15.0,
    width_cm: null,
    length_cm: null,
    suggested_dough_weight_min_g: 750,
    suggested_dough_weight_max_g: 780,
    notes: "Savory brioche - flat top",
  },
  {
    product_type: "Panettone Gastronomico",
    mold_rating: "1kg",
    height_cm: 12.5,
    diameter_cm: 17.0,
    width_cm: null,
    length_cm: null,
    suggested_dough_weight_min_g: 1000,
    suggested_dough_weight_max_g: 1050,
    notes: "Savory brioche - flat top",
  },
];
